### ISSUE TITLE
jQuery conflict

### ISSUE THREAD

**Issue by hellocosmin** [Cedriking/is.js#2]
Hi, congrats on this very nice looking library :)

So, first issue: it's not working if you run jQuery on the same page. Using latest jQuery as of now, version 2.1.3

Adding is.js *before* jQuery produces this error in jQuery (copied from Firebug):

<pre>TypeError: d[q] is not a function

...d[k],h&&(d[k]=null),n.event.triggered=q,d[q](),n.event.triggered=void 0,h&&(d[k]...</pre>

If you call is.js *after* jQuery, then you get this error:

<pre>TypeError: X[g].exec is not a function

....slice(c.length));for(g in d.filter)!(e=X[g].exec(h))||j[g]&&!(e=j[g](e))||(c=e....</pre>

This library looks like a must-have, but then again, jQuery is a must have. :)

**Comment by Cedriking** [comment]
Hello @hellocosmin , I'm going to check into this when I get back home, not sure what could be but remember that jQuery 2+ only works on modern browsers and is.js works on ie 6+ so maybe it has something to do with that.

**Comment by hellocosmin** [comment]
Are there any plans on moving forward and dropping such old browser support, in order to enable compatibility with future versions of jQuery?

The way I see it, the web is quickly moving towards adapting new versions of jQuery and dropping support for dinosaur browsers. It would mean less headaches for you too - perhaps a separate branch?

**Comment by Cedriking** [comment]
I though it was finally working fine, here is a simple working demo: http://jsfiddle.net/1z0vh5wp/
Can you show me your code or where are you getting this error?
