### ISSUE TITLE
isNumber is not defined

### ISSUE THREAD

**Issue by softwarespot** [Cedriking/is.js#4]
In isNaN, you use !this.isNumber(), though isNumber is not defined anywhere. Also isNaN ideally should be defined as ...

```js
function isNaN(value) {
    return this.isNumber(value) && value !== value;
}
```

**Comment by Cedriking** [comment]
isNumber is defined in the each function https://github.com/Cedriking/is.js/blob/master/is.js#L69

**Comment by softwarespot** [comment]
Ah, my bad. A simple oversight on my part. Sorry
